name: Bem Vindo ao meu Blog
description: Blog Anderson Cirilo Valentim
meta_description: "Bem vindos ao meu Blog, irei falar de tudo que mais gosto: Música, programação e Segurança"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
